clip_processor_num = 1
comment_processor_num = 1
request_limit = 5
log_level = "info"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"

[db]
driver = "postgres"
dsn = "host=localhost user=postgres password=postgres dbname=ddc TimeZone=Asia/Shanghai"
max_idle_conn = 5
max_open_conn = 5
